export const REQUEST_REVIEW_LIST_TO_DJANGO = 'REQUEST_REVIEW_LIST_TO_DJANGO';
export const REQUEST_REVIEW_TO_DJANGO = 'REQUEST_REVIEW_TO_DJANGO'
export const INCREMENT_REVIEW_VIEW_COUNT = 'INCREMENT_REVIEW_VIEW_COUNT'